### PR TITLE
neovim-python: version bump to 0.2.6

### PR DESCRIPTION
**Pull request by kapsh**

### CODE REVIEW

**Comment by medvid** [comment]
src_test phase fails with asyncio error for python_abis:2.7:

http://ix.io/1kDO

[1m[31mbuild/lib/neovim/msgpack_rpc/event_loop/base.py[0m:92: RuntimeError
--------------------------------------------------------------------------- Captured log setup ---------------------------------------------------------------------------
base_events.py            1053 ERROR    Exception in callback pipe_data_received(2, 'nvim: error ...r directory\n')
handle: <Handle pipe_data_received(2, 'nvim: error ...r directory\n')>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/trollius/events.py", line 136, in _run
    self._callback(*self._args)
  File "/var/tmp/paludis/build/dev-python-neovim-python-0.2.6/work/PYTHON_ABIS/2.7/python-client-0.2.6/build/lib/neovim/msgpack_rpc/event_loop/asyncio.py", line 64, in pipe_data_received
    self._on_stderr(data)
AttributeError: 'AsyncioEventLoop' object has no attribute '_on_stderr'
[1m[31m======================================================================= 56 error in 12.78 seconds ========================================================================[0m

**Comment by kapsh** [comment]
Weird, it passed for me yesterday and now https://paste.pound-python.org/show/NXoLY6n2G3og1ub8NN2O/

Did you update trollius before this?

**Comment by medvid** [comment]
Yes I suspected trollius update was the reason, but the test failed identically with trollius-2.0 and trollius-2.2.
Will investigate the failure.

**Comment by kapsh** [comment]
I also checked with trollius 2.0 and 2.2, both passed. Tried to run with previous neovim version, but tests then fail earlier.

**Comment by kapsh** [comment]
@medvid hello, did you found anything interesting?

**Comment by medvid** [comment]
I did a testing on another exherbo box (x86_64), and the src_test passed. Likely misconfiguration on the aarch64 laptop.

**Comment by medvid** [comment]
Therefore, I merged the update. Thank you!

**Pull request merged**
