### PR TITLE
neovim: version bump to 0.3.1

### PR DESCRIPTION
**Pull request by kapsh**

### CODE REVIEW

**Comment by hasufell** [comment]
Please add missing desktop database update:

```diff
--- a/packages/app-editors/neovim/neovim.exlib
+++ b/packages/app-editors/neovim/neovim.exlib
@@ -3,6 +3,7 @@
 # Distributed under the terms of the GNU General Public License v2

 require alternatives github [ user=neovim tag=v${PV} ] cmake [ api=2 cm$
+require freedesktop-desktop

 SUMMARY="Vim's rebirth for the 21st century"
 DESCRIPTION="
@@ -61,3 +62,8 @@ src_install() {
     alternatives_for vi ${PN} 75 /usr/share/man/man1/vi.1 nvim.1
 }

+pkg_postinst() {
+    freedesktop-desktop_pkg_postinst
+    alternatives_pkg_postinst
+}
+
```

**Comment by kapsh** [comment]
Thank you @hasufell 
Updated.

**Comment by hasufell** [comment]
This is not a trivial package, so please update this or let someone else maintain. Exherbo policy of responsiveness is one month, this is **way** beyond it.

**Comment by medvid** [comment]
Thank you!

**Pull request merged**
